Book.create([
  { title: "The Great Gatsby", author: "F. Scott Fitzgerald", available: true },
  { title: "1984", author: "George Orwell", available: false },
  { title: "To Kill a Mockingbird", author: "Harper Lee", available: true },
  { title: "Pride and Prejudice", author: "Jane Austen", available: true },
  { title: "Moby-Dick", author: "Herman Melville", available: false },
  { title: "War and Peace", author: "Leo Tolstoy", available: true },
  { title: "The Catcher in the Rye", author: "J.D. Salinger", available: false },
  { title: "The Hobbit", author: "J.R.R. Tolkien", available: true },
  { title: "Jane Eyre", author: "Charlotte Brontë", available: true },
  { title: "Brave New World", author: "Aldous Huxley", available: false },
  { title: "Crime and Punishment", author: "Fyodor Dostoevsky", available: true },
  { title: "The Odyssey", author: "Homer", available: true },
  { title: "Wuthering Heights", author: "Emily Brontë", available: false },
  { title: "Frankenstein", author: "Mary Shelley", available: true },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", available: true },
  { title: "A Little Life", author: "Hanya Yanagihara", available: true },
  { title: "The Tipping Point", author: "Malcolm Gladwell", available: true },
  { title: "Darkmans", author: "Nicola Barker", available: true },
  { title: "The Siege", author: "Helen Dunmore", available: true },
  { title: "Light", author: "M John Harrison", available: true },
  { title: "Bad Blood", author: "Lorna Sage", available: true },
  { title: "Adults in the Room", author: "Yanis Varoufakis", available: true },
  { title: "The Cost of Living", author: "Deborah Levy", available: true },
  { title: "Coraline", author: "Neil Gaiman", available: true }
])
